### PR TITLE
Adjust datefield

### PR DESCRIPTION
**Pull request by sebald**

### CODE REVIEW

**Comment by sarahgm** [comment]
@sebald  typecheck and test :o

**Comment by sarahgm** [comment]
@sebald  what about these lint warnings? Should this be resolved?

**Comment by sebald** [comment]
> @sebald  what about these lint warnings? Should this be resolved?

Maybe we should change then to be an error?

**Comment by sebald** [comment]
> @sebald yes do you know how? I can merge this than, right?

Yes.

For the lint stuff: needs to be changed in our config

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
