### PR TITLE
[DST-110]: Share `Field` Styles across multiple Components

### PR DESCRIPTION
**Pull request by OsamaAbdellateef**

### CODE REVIEW

**Comment by sarahgm** [comment]
what is with the other form components? Isn't it also possible? @OsamaAbdellateef

**Comment by OsamaAbdellateef** [comment]
> what is with the other form components? Isn't it also possible? @OsamaAbdellateef



> what is with the other form components? Isn't it also possible? @OsamaAbdellateef
@sarahgm 
like what ?

**Comment by sarahgm** [comment]
> > what is with the other form components? Isn't it also possible? @OsamaAbdellateef
> 
> > what is with the other form components? Isn't it also possible? @OsamaAbdellateef
> > @sarahgm
> > like what ?

to use the styles? DateField, TextField and so on :D I was just wondering

**Comment by OsamaAbdellateef** [comment]
> > > what is with the other form components? Isn't it also possible? @OsamaAbdellateef
> > 
> > 
> > > what is with the other form components? Isn't it also possible? @OsamaAbdellateef
> > > @sarahgm
> > > like what ?
> 
> to use the styles? DateField, TextField and so on :D I was just wondering @OsamaAbdellateef

@sarahgm 
Yeah most of them are unified because they use the same `Input` component but not all of them, and i added styles for components that aren't using `Input`

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
