### PR TITLE
test shiki update

### PR DESCRIPTION
**Pull request by sarahgm**

### CODE REVIEW

**Comment by sarahgm** [comment]
https://github.com/vercel/next.js/issues/58576

**Comment by sarahgm** [comment]
Thing that isn't working is: the demos are undefined. @aromko and I tried to solve it, but we haven't a good idea why it is like this. If you want to you can also try to solve it. @OsamaAbdellateef @sebald

**Comment by sebald** [comment]
Maybe something for mob?

**Comment by sarahgm** [comment]
https://github.com/contentlayerdev/contentlayer/issues/575

**Comment by sarahgm** [comment]
> docs
├─┬ contentlayer 0.3.4
│ └─┬ @contentlayer/cli 0.3.4
│   └─┬ @contentlayer/core 0.3.4
│     ├── ✕ unmet peer esbuild@"0.17.x || 0.18.x": found 0.19.10
│     └─┬ @contentlayer/utils 0.3.4
│       └─┬ @opentelemetry/exporter-trace-otlp-grpc 0.39.1
│         ├─┬ @opentelemetry/core 1.13.0
│         │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
│         └─┬ @opentelemetry/otlp-transformer 0.39.1
│           ├── ✕ unmet peer @opentelemetry/api@">=1.3.0 <1.5.0": found 1.7.0 in @contentlayer/utils
│           ├─┬ @opentelemetry/resources 1.13.0
│           │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
│           ├─┬ @opentelemetry/sdk-logs 0.39.1
│           │ └── ✕ unmet peer @opentelemetry/api@">=1.4.0 <1.5.0": found 1.7.0 in @contentlayer/utils
│           ├─┬ @opentelemetry/sdk-metrics 1.13.0
│           │ └── ✕ unmet peer @opentelemetry/api@">=1.3.0 <1.5.0": found 1.7.0 in @contentlayer/utils
│           └─┬ @opentelemetry/sdk-trace-base 1.13.0
│             └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
└─┬ next-contentlayer 0.3.4
  └── ✕ unmet peer next@"^12 || ^13": found 14.1.2

Done in 36s

**Comment by sarahgm** [comment]
> > docs
> > ├─┬ contentlayer 0.3.4
> > │ └─┬ @contentlayer/cli 0.3.4
> > │   └─┬ @contentlayer/core 0.3.4
> > │     ├── ✕ unmet peer esbuild@"0.17.x || 0.18.x": found 0.19.10
> > │     └─┬ @contentlayer/utils 0.3.4
> > │       └─┬ @opentelemetry/exporter-trace-otlp-grpc 0.39.1
> > │         ├─┬ @opentelemetry/core 1.13.0
> > │         │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > │         └─┬ @opentelemetry/otlp-transformer 0.39.1
> > │           ├── ✕ unmet peer @opentelemetry/api@">=1.3.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > │           ├─┬ @opentelemetry/resources 1.13.0
> > │           │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > │           ├─┬ @opentelemetry/sdk-logs 0.39.1
> > │           │ └── ✕ unmet peer @opentelemetry/api@">=1.4.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > │           ├─┬ @opentelemetry/sdk-metrics 1.13.0
> > │           │ └── ✕ unmet peer @opentelemetry/api@">=1.3.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > │           └─┬ @opentelemetry/sdk-trace-base 1.13.0
> > │             └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.5.0": found 1.7.0 in @contentlayer/utils
> > └─┬ next-contentlayer 0.3.4
> > └── ✕ unmet peer next@"^12 || ^13": found 14.1.2
> 
> Done in 36s

tried to solve it adding this in the package.json:
` "overrides": {
    "next-contentlayer": {
      "next": "$next"
    },    
    "contentlayer": {
      "esbuild@": "0.18.x"
    }
  },`

**Comment by sarahgm** [comment]
running: `pnpm contentlayer build` => `TypeError: The "code" argument must be of type number. Received an instance of Object` :S

**Comment by sarahgm** [comment]
https://github.com/contentlayerdev/contentlayer/pull/599

**Comment by aromko** [comment]
> [!IMPORTANT]  
> It seems like this is an issue with `contentlayer` as long there is no way to update it updating `rehype` plugins might not work. We wait if the project ist picked up again, if not we have to find an alternative. See https://github.com/contentlayerdev/contentlayer/issues/429.
> Possible alternative: https://www.mdxts.dev/

**Pull request closed without merging**
