### PR TITLE
fix(eslint): Repair weird eslint incompatibilities

### PR DESCRIPTION
**Pull request by sebald**
Don't ask me ... it works again

### CODE REVIEW

**Comment by ti10le** [comment]
@sebald doesn't work for me 😔🤔

**Comment by sebald** [comment]
> @sebald doesn't work for me 😔🤔

What's the error?

**Comment by ti10le** [comment]
> > @sebald doesn't work for me 😔🤔
> 
> What's the error? Because it works on the CI.

same as before:
image

CI also had no error before

**Comment by viktoria-schwarz** [comment]
> > > @sebald doesn't work for me pensivethinking
> > 
> > 
> > What's the error? Because it works on the CI.
> 
> same as before:
> image
> 
> CI also had no error before

For me it works. @ti01le did you do `yarn` ?

**Comment by ti10le** [comment]
@viktoria-schwarz @sebald Yes it works! 😊

**Review by ti10le — APPROVED** [review]

**Pull request merged**
