### PR TITLE
Image component to gatsby docs

### LINKED ISSUE #1116: Add Image component to marigold docs
## Description

We need our own Image component like all other components in marigold docs.
To reach this we have to show our image component in action. This means you can show an image with marigold image component in gatsby.

## Context

Our target is to have all components from marigold storybook in gatsby docs.

## Consequences

we have a complete palette of our components on marigold docs page

### PR DESCRIPTION
**Pull request by ti10le**
closes #1116

### CODE REVIEW

**Review by sebald — CHANGES_REQUESTED** [review]
If you just want to show a component you can import it. See: https://mdxjs.com/getting-started#imports

**Comment by ti10le** [comment]
> If you just want to show a component you can import it. See: [mdxjs.com/getting-started#imports](https://mdxjs.com/getting-started#imports)

oooh sure 🙂 thought to complicated

**Comment by sebald** [comment]
> > If you just want to show a component you can import it. See: [mdxjs.com/getting-started#imports](https://mdxjs.com/getting-started#imports)
> 
> oooh sure 🙂 thought to complicated

A regular import is more complicated than to implement an already existing feature which uses a codeblock to not show code but rather render a component? 🤪

**Comment by ti10le** [comment]
> > > If you just want to show a component you can import it. See: [mdxjs.com/getting-started#imports](https://mdxjs.com/getting-started#imports)
> > 
> > 
> > oooh sure 🙂 thought to complicated
> 
> A regular import is more complicated than to implement an already existing feature which uses a codeblock to not show code but rather render a component? 🤪

No i meant my thoughts were to complicated to use the existing Logo component like you proposed 😀 It's much better know

**Review by viktoria-schwarz — APPROVED** [review]

**Pull request merged**
