### PR TITLE
[DST-159]: Remove "@testing-library/react-hooks"

### PR DESCRIPTION
**Pull request by OsamaAbdellateef**

### CODE REVIEW

**Comment by sarahgm** [comment]
Hey @OsamaAbdellateef are you still on this or is it ready for rewiew?

**Comment by sarahgm** [comment]
In `ThemeSwitch.test.tsx` still `'@testing-library/react-hooks';` is used

**Comment by sarahgm** [comment]
@OsamaAbdellateef  hm...  what have you tired out?

**Comment by OsamaAbdellateef** [comment]
> @OsamaAbdellateef hm... what have you tired out?

I will let you know in details in meeting @sarahgm

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
