### PR TITLE
[DST-63]: Adding`useSmallScreen` hook

### PR DESCRIPTION
**Pull request by OsamaAbdellateef**

### CODE REVIEW

**Comment by sebald** [comment]
@OsamaAbdellateef can you also use it in components previously used `useResponsive` hook? :)

**Comment by OsamaAbdellateef** [comment]
> > @OsamaAbdellateef can you also use it in components previously used `useResponsive` hook? :)
> 
> @sebald   Done 100

**Comment by sebald** [comment]
There is an issue with the docs build, guess we have to check if window exists 🙈

**Comment by OsamaAbdellateef** [comment]
> There is an issue with the docs build, guess we have to check if window exists see_no_evil

@sebald  Done :ballot_box_with_check:

**Review by sebald — APPROVED** [review]

**Pull request merged**
