### PR TITLE
chore: fix lint error

### PR DESCRIPTION
**Pull request by sebald**

### CODE REVIEW

**Comment by sarahgm** [comment]
lint error is still there 🤔

**Comment by sebald** [comment]
> lint error is still there 🤔

@sarahgm :-0 where!?

**Comment by sarahgm** [comment]
> > lint error is still there 🤔
> 
> @sarahgm :-0 where!?

It says when you click on files change: 
```The href attribute requires a valid value to be accessible.```

Or am just confused :D

**Comment by sebald** [comment]
@sarahgm ... fixed it ... this time ... maaaaaybe >.<

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
