### PR TITLE
[DST-514]: Revise "Tag" page 

### PR DESCRIPTION
**Pull request by OsamaAbdellateef**
# Description

Revise `<Tag>` component according to our https://reservix.atlassian.net/wiki/spaces/DST/pages/2777939985/Template+Component+Page

# Reviewers:

@marigold-ui/developer
@marigold-ui/designer
@KadaStrophe

### CODE REVIEW

**Review by KadaStrophe — COMMENTED** [review]
Good job

**Comment by sarahgm** [comment]
Hi @OsamaAbdellateef  here are ttwo open comments left, do you have it in mind?

**Comment by sebald** [comment]
Can we help to get this over the finish line? :)

**Comment by OsamaAbdellateef** [comment]
> Can we help to get this over the finish line? :)

from my side nothing new to add i resolved all the comments @sebald

**Review by KadaStrophe — APPROVED** [review]

**Pull request merged**
