### PR TITLE
docs: move resources pages to introduction (and hide develoepr guidelines)

### PR DESCRIPTION
**Pull request by sebald**
# Reviewers:

@marigold-ui/developer
@marigold-ui/designer

### CODE REVIEW

**Comment by sarahgm** [comment]
@sebald can you add this to the toc? Currently when you type internal inside of it it shows the internal page, but no subpages

**Comment by sebald** [comment]
@sarahgm what is "this"? :D

**Comment by sarahgm** [comment]
> @sarahgm what is "this"? :D

Can you add the page "Code Guidelines" or how it is called to the command menu, because currently is not, only internal

**Comment by sarahgm** [comment]
> > > @sarahgm what is "this"? :D
> > 
> > 
> > Can you add the page "Code Guidelines" or how it is called to the command menu, because currently is not, only internal @sebald
> 
> But then it will show up there, right? I think this shouldn't be a public page

I mean like we have with internal page.... if you type in internal in the command it will appear - i think it was also your idea :/

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
