### PR TITLE
Tailwind calendar

### PR DESCRIPTION
**Pull request by OsamaAbdellateef**

### CODE REVIEW

**Review by OsamaAbdellateef — COMMENTED** [review]
Reviewed

**Review by OsamaAbdellateef — COMMENTED** [review]
Reviewed

**Comment by sarahgm** [comment]
@OsamaAbdellateef  why do you have tabs in there?

**Comment by OsamaAbdellateef** [comment]
> @OsamaAbdellateef why do you have tabs in there?

PR is fixed now

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
