### PR TITLE
refa: use non-rac checkbox in table

### PR DESCRIPTION
**Pull request by sebald**

### CODE REVIEW

**Comment by sebald** [comment]
@OsamaAbdellateef @sarahgm this makes it work again (AFAIK) but the checkboxes in the row are not styled anymore. why? :-O

**Comment by sarahgm** [comment]
> @OsamaAbdellateef @sarahgm this makes it work again (AFAIK) but the checkboxes in the row are not styled anymore. why? :-O

maybe because the classnames slipped to another element?

**Comment by sarahgm** [comment]
> > > @OsamaAbdellateef @sarahgm this makes it work again (AFAIK) but the checkboxes in the row are not styled anymore. why? :-O
> > 
> > 
> > maybe because the classnames slipped to another element?
> 
> But there is no className involved 🤔 or is there?

I think about className.checkbox :)

**Comment by sebald** [comment]
superseeded by #3451

**Pull request closed without merging**
