### PR TITLE
chore: fix docs deployment

### PR DESCRIPTION
**Pull request by sebald**

### CODE REVIEW

**Comment by sarahgm** [comment]
@sebald when i check this out and try to run it it failes

> Generating JavaScript bundles failed
Unknown option: .resourceQuery.

**Comment by sebald** [comment]
@sarahgm does the main branch work?

**Comment by sebald** [comment]
Ah I think our docs build is broken, we need to get the new ones done 🙈

**Comment by sarahgm** [comment]
@sebald has this worked at some point? Can this PR be closed?

**Comment by sebald** [comment]
This does only fix deployment. Not the build itself :/

**Review by sarahgm — APPROVED** [review]

**Pull request merged**
